export const TITLE = '¡Contribuye con nosotros!'
export const TEXT = '¡Únete a nuestro equipo en Farm Habit! Si eres una persona apasionada por la salud y el bienestar, te invitamos a ser parte de nuestro proyecto para ayudar a más personas a construir hábitos saludables. ¡Tu aporte puede hacer una gran diferencia!'
export const LINK = ''
export const TEXT_LINK = 'Haz clic aquí'
export const TEXT_AFTER = 'para acceder a nuestro repositorio.'
export const TEXT_BEFORE = 'También puedes contribuir a nuestro proyecto en GitHub.'