export const TITLE = 'Cultiva un nuevo'
export const TITLE_SPECIAL = 'hábito'
export const TEXT = 'Cada hábito que cultivas es una semilla que plantas para tu futuro'
export const BUTTON_DOWNLOWAD = 'Descargar'
export const BUTTON_KNOW = 'Conoce la aplicación '